/* posix_time_config.h.  Generated by configure.  */
/* posix_time_config.h.in.  Generated from configure.ac by autoheader.  */

/* Define to 1 if the system has the type `clockid_t'. */
#define HAVE_CLOCKID_T 1

/* Define to 1 if you have the `clock_getres' function. */
/* #undef HAVE_CLOCK_GETRES */

/* Define to 1 if you have the `clock_gettime' function. */
/* #undef HAVE_CLOCK_GETTIME */

/* Define to 1 if you have the `clock_nanosleep' function. */
/* #undef HAVE_CLOCK_NANOSLEEP */

/* Define to 1 if you have the `clock_settime' function. */
/* #undef HAVE_CLOCK_SETTIME */

/* Define to 1 if you have the declaration of `clock_getres', and to 0 if you
   don't. */
#define HAVE_DECL_CLOCK_GETRES 1

/* Define to 1 if you have the declaration of `clock_gettime', and to 0 if you
   don't. */
#define HAVE_DECL_CLOCK_GETTIME 1

/* Define to 1 if you have the declaration of `clock_nanosleep', and to 0 if
   you don't. */
#define HAVE_DECL_CLOCK_NANOSLEEP 0

/* Define to 1 if you have the declaration of `clock_settime', and to 0 if you
   don't. */
#define HAVE_DECL_CLOCK_SETTIME 1

/* Define to 1 if you have the declaration of `timer_create', and to 0 if you
   don't. */
#define HAVE_DECL_TIMER_CREATE 1

/* Define to 1 if you have the declaration of `timer_delete', and to 0 if you
   don't. */
#define HAVE_DECL_TIMER_DELETE 1

/* Define to 1 if you have the declaration of `timer_getoverrun', and to 0 if
   you don't. */
#define HAVE_DECL_TIMER_GETOVERRUN 1

/* Define to 1 if you have the declaration of `timer_gettime', and to 0 if you
   don't. */
#define HAVE_DECL_TIMER_GETTIME 1

/* Define to 1 if you have the declaration of `timer_settime', and to 0 if you
   don't. */
#define HAVE_DECL_TIMER_SETTIME 1

/* Define to 1 if you have the <dlfcn.h> header file. */
#define HAVE_DLFCN_H 1

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* Define to 1 if the system has the type `siginfo_t'. */
#define HAVE_SIGINFO_T 1

/* Define to 1 if `si_overrun' is member of `siginfo_t'. */
#define HAVE_SIGINFO_T_SI_OVERRUN 1

/* Define to 1 if `si_tid' is member of `siginfo_t'. */
/* #undef HAVE_SIGINFO_T_SI_TID */

/* Define to 1 if `si_timer1' is member of `siginfo_t'. */
/* #undef HAVE_SIGINFO_T_SI_TIMER1 */

/* Define to 1 if `si_timer2' is member of `siginfo_t'. */
/* #undef HAVE_SIGINFO_T_SI_TIMER2 */

/* Define to 1 if `si_timerid' is member of `siginfo_t'. */
#define HAVE_SIGINFO_T_SI_TIMERID 1

/* Define to 1 if `_sifields' is member of `siginfo_t'. */
#define HAVE_SIGINFO_T__SIFIELDS 1

/* Define to 1 if `_sifields._timer' is member of `siginfo_t'. */
#define HAVE_SIGINFO_T__SIFIELDS__TIMER 1

/* Define to 1 if you have the <signal.h> header file. */
#define HAVE_SIGNAL_H 1

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if the system has the type `struct itimerspec'. */
#define HAVE_STRUCT_ITIMERSPEC 1

/* Define to 1 if the system has the type `struct sigevent'. */
#define HAVE_STRUCT_SIGEVENT 1

/* Define to 1 if the system has the type `struct timespec'. */
#define HAVE_STRUCT_TIMESPEC 1

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the `timer_create' function. */
/* #undef HAVE_TIMER_CREATE */

/* Define to 1 if you have the `timer_delete' function. */
/* #undef HAVE_TIMER_DELETE */

/* Define to 1 if you have the `timer_getoverrun' function. */
/* #undef HAVE_TIMER_GETOVERRUN */

/* Define to 1 if you have the `timer_gettime' function. */
/* #undef HAVE_TIMER_GETTIME */

/* Define to 1 if you have the `timer_settime' function. */
/* #undef HAVE_TIMER_SETTIME */

/* Define to 1 if the system has the type `timer_t'. */
#define HAVE_TIMER_T 1

/* Define to 1 if you have the <time.h> header file. */
#define HAVE_TIME_H 1

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* Name of package */
#define PACKAGE "hrtimers-support"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT ""

/* Define to the full name of this package. */
#define PACKAGE_NAME ""

/* Define to the full name and version of this package. */
#define PACKAGE_STRING ""

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME ""

/* Define to the version of this package. */
#define PACKAGE_VERSION ""

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* Version number of package */
#define VERSION "3.1.1"
